### ISSUE TITLE
Idea/asking for help with big clock

### ISSUE THREAD

**Issue by stewe12** [hermannsblum/kindle_infoscreen#24]
I tried your script and fell in love! It is great and works on Kindle Touch without any problems. You can see it on my Kindle in this Imgur:
<blockquote class="imgur-embed-pub" lang="en" data-id="a/4vWKJhK"  ><a href="//imgur.com/a/4vWKJhK">Home assistant + Kindle Touch</a></blockquote>

But I would like to ask for a little bit of help, maybe as an idea... My Kindle is kind of center piece of our home - mainly for checking time, but we have also temperatures, CO2 levels and small forecast. It is website built in Wordpress and shown on Kindle. You can check it here: http://kindle.g6.cz

Control panel of my dreams would have big time displayed with temperatures, easily readable from 2 meters away and ability to control all of my smart home.

Is there any easy way how I can add big clock on top of your dashboard?

I tried to make href from my Wordpress to local file and back for switching, but Kindle won't open local filem from that website.

**Comment by hermannsblum** [comment]
Hi! Glad that you like this 👍 
To add a big clock on top of the dashboard, you could just add a `div` [here](https://github.com/hermannsblum/kindle_infoscreen/blob/a8134049980e5fe1f81db5b9eaa313ce9eb9d38a/src/index.js#L254):
```
return m('div', [
  m('div', {style: {'font-size': 100px } } , `${get current time from javascript()}`),
  ...
```

Also, for switching back and forth, since the file-url does not work, another approach that some people told me is that they put the file on their home-assistant instead of the kindle, and can then reach the file via a web address. See [this comment](https://github.com/hermannsblum/kindle_infoscreen/issues/12#issuecomment-668879024).
Let me know how it works!

**Comment by stewe12** [comment]
It doesn't work. I am sorry, but I am not that skilled in JS and it is probably my fault.

It doesn't like the font size 100px, but when I remove style, it says unexpected token for "current time from javascript()".

And the www folder is great idea! I am gonna do that for faster edits and wireless uploads of new dashboards.

**Comment by hermannsblum** [comment]
oh, sorry, the font size should indeed be in a string, '100px'

and for the javascript: That was just a placeholder, not actual code ;)
You can replace it eg with this [here](https://www.w3schools.com/jsref/jsref_tolocaletimestring.asp).
